name = "SfDynamics"
uuid = "e64c2703-cb32-456a-8d09-768f0ca3a885"
authors = ["I Can't Believe It's Not Physics <icantbelieveitsnotphysics@runbox.no>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
